Update flags table on README (#204)
* Updated Gym Layout

Gym Layout now contains Icons like the rest of the items (except
Pokeballs)

* Update flags table

* Reformat get_args

* Update flags table

* Reformat get_args

* Add autorefresh flag to README

* Update flags table

* Reformat get_args

* added countdown timer until pokemon disappear

* changed the label so it displays both disappears-at and disappears-in

* changed label format

* Fix multiline string

* decoupled google maps from flask

* removed one more thing

* Cleaned up duplicate and unused imports.

* added some nice autoupdate fixes

* fix DecodeError crash

Completed: 59.5555555556%
[-] looping: step 135 of 225
Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 575, in main
    pokemonsJSON, ignore, only)
  File "example.py", line 600, in process_step
    profile_response))
  File "example.py", line 399, in get_heartbeat
    m5, )
  File "example.py", line 304, in get_profile
    return retrying_api_req(service, api, access_token, req, useauth=useauth)
  File "example.py", line 190, in retrying_api_req
    **kwargs)
  File "example.py", line 228, in api_req
    p_ret.ParseFromString(r.content)
  File "/usr/lib/python2.7/site-packages/google/protobuf/message.py", line 186, in ParseFromString
    self.MergeFromString(serialized)
  File "/usr/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 844, in MergeFromString
    raise message_mod.DecodeError('Unexpected end-group tag.')
DecodeError: Unexpected end-group tag.

* Fix for scanner drift (fixes #229 and #231)

1. Quickfix for scanner slowly drifting away from starting location:
  reset location to original at the end of looping steps

2. Also fix updating to the next location feature:
  don't update repeatedly and allow to change only longitude or latitude

* more autoupdate fixes

* Add 'Get Directions' to label

- Add link to google maps directions
- Move index to right of Pokemon name

* ugly hack to keep google flask AND autorefresh functionality

* Added support for Simplified Chinese(zh_cn) pokemon names.

Based on
https://wiki.52poke.com/wiki/%E5%AE%9D%E5%8F%AF%E6%A2%A6%E5%88%97%E8%A1%A8%EF%BC%88%E6%8C%89%E5%85%A8%E5%9B%BD%E5%9B%BE%E9%89%B4%E7%BC%96%E5%8F%B7%EF%BC%89/%E7%AE%80%E5%8D%95%E7%89%88

* Option description update.

* remove marker if duplicate exists

* Fix "AttributeError: lat and lng required" when using coordinates as location (#241)

Previously, origin_lat and origin_lon was not set, causing an Attribute error when accessing the webpage.

* Fixed typo

Removed unnecessary braces

* added smaller images

* Fixed mobile scaling (#240)

* Step fix (#252)

* fixed the pokestop icon


* rebased the poke stop icon

* fixed display of steps and completion, fixed steplimit logic

* Reformat get_args

* Update flags table

* Add autorefresh flag to README

* Fix multiline string